export { default as Background } from "./background";
export { default as NavBar } from "./navBar";
export { default as Warper } from "./warper";
export { default as Home } from "./home";
export { default as About } from "./about";
export { default as Footer } from "./footer";
export { default as Expertise } from "./expertise";
export { default as Hobbies } from "./hobbies";
export { default as Contact } from "./contact";
